### PR TITLE
Clean up Ruby version settings

### PR DESCRIPTION
**Pull request by farski**

### CODE REVIEW

**Comment by cqr** [comment]
@farski This project is dead, correct?

**Comment by farski** [comment]
@chrisrhoden Yes, should we remove the repo?

**Comment by kookster** [comment]
@farski Where is the code, however small it may be, for the lambda?

**Comment by farski** [comment]
Currently only in lambda

**Comment by kookster** [comment]
We need a better way to handle lambdas.
Perhaps a new lambda repo for all such projects?
Perhaps a gist for the prx org?

**Pull request merged**
